export const CipherStreamABI = [
  {
    inputs: [],
    stateMutability: "nonpayable" as const,
    type: "constructor" as const,
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "videoId", type: "uint256" as const },
      { indexed: true, internalType: "address", name: "viewer", type: "address" as const },
      { indexed: false, internalType: "uint256", name: "expiry", type: "uint256" as const },
    ],
    name: "AccessUnlocked",
    type: "event" as const,
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "videoId", type: "uint256" as const },
      { indexed: true, internalType: "address", name: "creator", type: "address" as const },
      { indexed: false, internalType: "string", name: "title", type: "string" as const },
      { indexed: false, internalType: "uint256", name: "price", type: "uint256" as const },
    ],
    name: "VideoCreated",
    type: "event" as const,
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "videoId", type: "uint256" as const },
      { indexed: false, internalType: "bool", name: "active", type: "bool" as const },
    ],
    name: "VideoStatusChanged",
    type: "event" as const,
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "creator", type: "address" as const },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" as const },
    ],
    name: "Withdrawal",
    type: "event" as const,
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" as const },
      { internalType: "address", name: "", type: "address" as const },
    ],
    name: "accessExpiry",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [
      { internalType: "string", name: "title", type: "string" as const },
      { internalType: "string", name: "description", type: "string" as const },
      { internalType: "string", name: "encryptedVideoCID", type: "string" as const },
      { internalType: "string", name: "thumbnailCID", type: "string" as const },
      { internalType: "uint256", name: "price", type: "uint256" as const },
      { internalType: "uint256", name: "accessDuration", type: "uint256" as const },
    ],
    name: "createVideo",
    outputs: [],
    stateMutability: "nonpayable" as const,
    type: "function" as const,
  },
  {
    inputs: [],
    name: "getAllVideos",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" as const },
          { internalType: "address", name: "creator", type: "address" as const },
          { internalType: "string", name: "title", type: "string" as const },
          { internalType: "string", name: "description", type: "string" as const },
          { internalType: "string", name: "encryptedVideoCID", type: "string" as const },
          { internalType: "string", name: "thumbnailCID", type: "string" as const },
          { internalType: "uint256", name: "price", type: "uint256" as const },
          { internalType: "uint256", name: "accessDuration", type: "uint256" as const },
          { internalType: "uint256", name: "createdAt", type: "uint256" as const },
          { internalType: "bool", name: "active", type: "bool" as const },
        ],
        internalType: "struct CipherStream.Video[]",
        name: "",
        type: "tuple[]" as const,
      },
    ],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [
      { internalType: "uint256", name: "videoId", type: "uint256" as const },
      { internalType: "address", name: "viewer", type: "address" as const },
    ],
    name: "getAccessExpiry",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [{ internalType: "address", name: "creator", type: "address" as const }],
    name: "getCreatorVideos",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" as const },
          { internalType: "address", name: "creator", type: "address" as const },
          { internalType: "string", name: "title", type: "string" as const },
          { internalType: "string", name: "description", type: "string" as const },
          { internalType: "string", name: "encryptedVideoCID", type: "string" as const },
          { internalType: "string", name: "thumbnailCID", type: "string" as const },
          { internalType: "uint256", name: "price", type: "uint256" as const },
          { internalType: "uint256", name: "accessDuration", type: "uint256" as const },
          { internalType: "uint256", name: "createdAt", type: "uint256" as const },
          { internalType: "bool", name: "active", type: "bool" as const },
        ],
        internalType: "struct CipherStream.Video[]",
        name: "",
        type: "tuple[]" as const,
      },
    ],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [{ internalType: "uint256", name: "videoId", type: "uint256" as const }],
    name: "getVideo",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" as const },
          { internalType: "address", name: "creator", type: "address" as const },
          { internalType: "string", name: "title", type: "string" as const },
          { internalType: "string", name: "description", type: "string" as const },
          { internalType: "string", name: "encryptedVideoCID", type: "string" as const },
          { internalType: "string", name: "thumbnailCID", type: "string" as const },
          { internalType: "uint256", name: "price", type: "uint256" as const },
          { internalType: "uint256", name: "accessDuration", type: "uint256" as const },
          { internalType: "uint256", name: "createdAt", type: "uint256" as const },
          { internalType: "bool", name: "active", type: "bool" as const },
        ],
        internalType: "struct CipherStream.Video",
        name: "",
        type: "tuple" as const,
      },
    ],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [
      { internalType: "uint256", name: "videoId", type: "uint256" as const },
      { internalType: "address", name: "viewer", type: "address" as const },
    ],
    name: "getViewerAccess",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [
      { internalType: "uint256", name: "videoId", type: "uint256" as const },
      { internalType: "address", name: "viewer", type: "address" as const },
    ],
    name: "hasAccess",
    outputs: [{ internalType: "bool", name: "", type: "bool" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" as const }],
    name: "pendingWithdrawals",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [
      { internalType: "uint256", name: "videoId", type: "uint256" as const },
      { internalType: "bool", name: "active", type: "bool" as const },
    ],
    name: "setVideoActive",
    outputs: [],
    stateMutability: "nonpayable" as const,
    type: "function" as const,
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    name: "unlockCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [{ internalType: "uint256", name: "videoId", type: "uint256" as const }],
    name: "unlockAccess",
    outputs: [],
    stateMutability: "payable" as const,
    type: "function" as const,
  },
  {
    inputs: [],
    name: "videoCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" as const }],
    name: "videos",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" as const },
      { internalType: "address", name: "creator", type: "address" as const },
      { internalType: "string", name: "title", type: "string" as const },
      { internalType: "string", name: "description", type: "string" as const },
      { internalType: "string", name: "encryptedVideoCID", type: "string" as const },
      { internalType: "string", name: "thumbnailCID", type: "string" as const },
      { internalType: "uint256", name: "price", type: "uint256" as const },
      { internalType: "uint256", name: "accessDuration", type: "uint256" as const },
      { internalType: "uint256", name: "createdAt", type: "uint256" as const },
      { internalType: "bool", name: "active", type: "bool" as const },
    ],
    stateMutability: "view" as const,
    type: "function" as const,
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable" as const,
    type: "function" as const,
  },
] as const;
